### ISSUE TITLE
Grading based on object(s) in `.result` and `.solution`

### ISSUE THREAD

**Issue by heanmaha** [rstudio/gradethis#268]
In this exercise student is guided to build a linear regression model and save it as object named `model1`. 

The solution code to the exercise looks like this:
`model1 <- lm(dist~speed, data = cars)`

**Instead of comparing just the input code from the user and the solution, I would want to check if the `model1` created in the exercise chunk (by the user) is equivalent to the `model1` in the solution.**

Grading would possibly work this way:
`pass_if(identical(get(model1, .result), get(model2, .solution)) `

Or somehow else. 

Importantly, it would be great to be able to get the objects constructed in the exercise and compare it to the object in the solution. If this is already possible, please let me know.

**Comment by rossellhayes** [comment]
`.result` and `.solution` hold the value of the last line of code in the `exercise` and `exercise-solution` chunks, so `pass_if_equal(.result, .solution)` would check that the student created the correct model.

But, it wouldn't check that the student had assigned the model to `model1`. To do that, you could use `pass_if_equal(get("model1", .envir_result), .solution)`.

For a more complete solution, you can add a failure message if `"model1"` does not exist, like so:

```` r
```{r exercise, exercise = TRUE}

```

```{r exercise-solution}
model1 <- lm(dist~speed, data = cars)
```

```{r exercise-check}
grade_this({
  fail_if(!exists("model1", .envir_result), "Remember to assign your model to an object called `model1`.")
  pass_if_equal(get("model1", .envir_result), .solution)
})
```
````

**Comment by heanmaha** [comment]
@rossellhayes , thank you for your response. I tried your check code and it seem'd to work - until I realised it just checks if student's answer to exercise is equal to model in .result. This happens to be (almost) always true. 
The parameter `.solution` in function `pass_if_equal` makes the checker to print the content of solution when the condition is true. So the code you shared didn't actually do what I wanted. 

I got a bit more familiar with the objects in the exercise and I improved the checker. The logic is supposed to work this way: 
- **FAIL** if there is no object `model1` in .result
- **FAIL** if the coefficients of result model and solution model differs (I limited this to check only 2 digits - due the numeric approach of linear regression in R the coefficients may differ a bit in last digits. If the models are completely different (f. ex. y and x are mixed), the coefficients differ from the beginning. 
- **PASS** if `model1` exists in `.result` and it's coefficients are identical (by two digits) to solution model. 
Here's the code I made: 

```
gradethis::grade_this({
  fail_if(!exists("model1", .envir_result), "Remember to save your model to object `model1`.")
  fail_if(!identical(format(get("model1", .envir_result)$coefficients, digits = 2), format(.solution$coefficients, digits = 2)), "Model is not correct. Please try again. You may have a hint when using `Hint`.")
  pass_if(exists("model1", .envir_result) && identical(format(get("model1", .envir_result)$coefficients, digits = 2), format(.solution$coefficients, digits = 2)), "Your model is correct. Yay!")
  fail()
})
```

The checker above satisfies my case. 
I have another question: Is it possible to access the solution enviroment the same way as result enviroment via `.env_result`? 

Thanks in advance for your help.

**Comment by gadenbuie** [comment]
Thanks @heanmaha for sharing your solution! Formatting the coefficients of the model seems like a reasonable way to check that the student provided the expected model.

To answer your question about how to access `model1` from the solution code: the result of the exercise solution is stored in `.solution`, but it isn't _evaluated_ unless you use it. We use [`delayedAssign()`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/delayedAssign) to create the object to only evaluate the code if `.solution` is used. This avoids some extra computation that might not be necessary.

So the first step to accessing an object created by the solution code is to evaluate `.solution`, which can be achieved by calling `force(.solution)` (or you could just use `.solution` in some way in your grading code).

The second step is where to look for any objects that were created by the solution code. The good news is you don't have to look to hard. We evaluate the solution code in the parent environment of the checking code... or in other words you can just refer to `model1` directly and it will be the `model1` created by the solution.

I put it all together into the grading code below. Along the way I made a few tweaks:

1. We have `fail_if()` for compatibility reasons, but for readability I highly prefer this style:

   ```r
   # instead of this version
   fail_if(!exists("model1", .envir_result, inherits = FALSE), "Remember to save your model object to `model1`.")

   # I prefer this version
   if (!exists("model1", .envir_result, inherits = FALSE)) {
     fail("Remember to save your model object to `model1`.")
   }
   ```

   I think it's easier to know from a glance that the failing feedback is provided _only_ if the condition in the `if()` statement is met.

2. The format above also encourages us to create intermediate variables, for example to store the users's `model1` in an intermediate object so we can refer to it repeatedly without having to use `get()`.

   ```r
   user_model1 <- get("model1", .envir_result, inherits = FALSE)
   ```

   We can then use `user_model1` to get the coefficients, but also to check that we have an `"lm"` model.

3. A small change: you can have identical models with terms specified in a different order, e.g. these both result in the same model filt:
   ```r
   lm(formula = mpg ~ disp + hp, data = mtcars)
   lm(formula = mpg ~ hp + disp, data = mtcars)
   ```

4. Finally, as you progress through your checks, you can be certain that the conditions that were checked earlier have all been satisfied. For example, if you check that

   1. The user created an object `model1`
   2. The user's `model1` obejct is an `lm` object
   3. The user's models coefficients match the solution

   when you get to the third check you don't need to include the conditions of the previous checks, since they're implied to have passed.

Okay, here's the refactored grading code with the above changes:

````markdown
```{r model-check}
grade_this({
  if (!exists("model1", .envir_result, inherits = FALSE)) {
    fail("Remember to save your model object to `model1`.")
  }
  
  # get the user's model and make sure that it's an `lm` object
  user_model1 <- get("model1", .envir_result, inherits = FALSE)
  if (!inherits(user_model1, "lm")) {
    fail("I expected `model1` to be a linear model created with the `lm()` function.", encourage = TRUE)
  }
  
  # get the coefficients of both models
  # (note we find the solution model in `model1`)
  force(.solution)
  soln_coefs <- format(model1$coefficients, digits = 2)  
  user_coefs <- format(user_model1$coefficients, digits = 2)
  
  # check the coefficient values using the term order of the solution
  if (!identical(user_coefs[names(soln_coefs)], soln_coefs)) {
    fail("Your model is not correct.", hint = TRUE, encourage = TRUE)
  }
  
  # if everything above was okay, then the model passes!
  pass("Your model is correct. Yay!")
})
```
````

**Comment by rossellhayes** [comment]
> @rossellhayes , thank you for your response. I tried your check code and it seem'd to work - until I realised it just checks if student's answer to exercise is equal to model in .result. This happens to be (almost) always true. The parameter `.solution` in function `pass_if_equal` makes the checker to print the content of solution when the condition is true. So the code you shared didn't actually do what I wanted.

Sorry, you're absolutely right about that. I had an error in my call to `pass_if_equal()` because I didn't use named arguments. I've updated the comment now so the code it contains should actually work.
