### ISSUE TITLE
Defaults to the first submission

### ISSUE THREAD

**Issue by thatSandemaboy** [rstudio/gradethis#279]
Is there any way we can get the gradethis check not to default to the first submission.
The issue is if the correct answer is "head(flights)" and student submits "head(flight)" first, it points out it's incorrect. Which is the expected reaction.

If the student resubmits "head(flights)", it subsequently marks it as correct. but when the answers to the codes are exported, it defaults to the first submission even though it was eventually changed.

**Comment by gadenbuie** [comment]
> but when the answers to the codes are exported, it defaults to the first submission even though it was eventually changed.

I'm not sure exactly how you're exporting the student's answers, but the methods provided by learnr by design report only the most recent submission. learnr tracks the state of the tutorial, not the history, since our primary goal is to help students pick up where the left off when they return to a tutorial.

If it's important for you to store each submission, you'll need to set up long-term storage and use [learnr's event recording](https://rstudio.github.io/learnr/articles/publishing.html#recording-events) (really event reporting) system to send tutorial events, like exercise submissions, to that storage.
