### ISSUE TITLE
Clarify difference between setup_global and setup_exercises

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/gradethis#363]
I am trying to use gradethis outside of the context of learnr and it appears that the best way to do this is via `mock_this_exercise()` which provides arguments `setup_global` and `setup_exercises`. 

Based on the documentation I cannot determine what the difference between these are. It appears that they both execute something prior to evaluating the submission.

Is there any other place in the docs that describe the difference between these?

**Comment by rossellhayes** [comment]
Hi Josiah,

`setup_global` mocks the contents of a tutorial-level setup chunk, while `setup_exercise` mocks the contents of a chunk that applies to only the exercise in question. For your use case, it sounds like using one or the other wouldn't make much practical difference, since you'd be specifying it at the exercise-level regardless. Both inputs exist for testing, because an exercise in a real tutorial may get setup code from either type of chunk.

**Comment by JosiahParry** [comment]
Thanks! I'm not sure I follow but I'll close this as it appears it doesn't matter :)
